config/routes.rb
Rails.application.routes.draw do
  root to: "urls#new"

  get "/urls", to: "urls#index", as: "urls" 

  get "/urls/new", to: "urls#new", as: "url_new" 

  post "/urls", to: "urls#create"

  get "/urls/:id", to: "urls#show", as: "url"

  get "/urls/:id/edit", to: "urls#edit" 

  put "/urls/:id", to: "urls#update"

  get "/go/:random_string", to: "urls#random_string"

  get "/go/:random_string/preview", to: "urls#preview" 

  get "/:my_string", to: "urls#my_string"


end 

# Rails convention: Model is always singular, table is always plural 

app/models/url.rb
class Url < ActiveRecord::Base
  has_many :visits

   validates :link, presence: true
   validates :random_string, presence: true, length: { minimum: 6, maximum: 10 }
   validates_uniqueness_of :random_string



   def self.find_url(random_string)
    @url = find_by(random_string: [random_string])
    Url.find(@url.id)
    # where("my_string = ?" OR "random_string = ?", random_string_or_my_string).find
    # self declares that the method will be performed on the entire table, not a single row. 
    # Use self when defining a class method. 
  end 

   def self.redirect_counter(random_string)
      @url = find_by(random_string: [random_string]) 
      Url.increment_counter(:count, @url.id) 
    end 

    def self.redirect_counter_my_string(my_string)
      @url = find_by(my_string: [my_string]) 
      Url.increment_counter(:count, @url.id) 
    end 

     before_validation :ensure_url_has_http 
protected
  # this is a callback 
   def ensure_url_has_http 
      unless link.start_with?("http://", "https://")
        self.link = "http://" + self.link
        # self.link is the link itself as a variable 
      end 
    end 

end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :url 
  

end
  

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/urls_controller.rb
class UrlsController < ApplicationController

  def new 
  end 

  def create
    url = params[:url].permit(:link, :random_string, :my_string)

    new_url = Url.create(url)
    new_url.random_string = SecureRandom.urlsafe_base64(5, true)
    new_url.save
    redirect_to url_path(new_url)
  end 

  def index 
    @urls = Url.all 
  end 

  def show 
    url = params[:id]
    @new_url = Url.find(url)
    @count = @new_url.count 

    # For showing timestamps of each visit. 
    @visits = @new_url.visits

  end 

  def edit 
    url_id = params[:id]
    @url = Url.find(url_id)
  end 

  def update 
    url_id = params[:id]
    @url = Url.find(url_id) 

    updated_url = params.require(:url).permit(:link, :random_string, :my_string) 
    @url.update_attributes(updated_url)

    redirect_to "/urls/#{url_id}"
  end 

  def index 
    @urls = Url.all
  end 

  def random_string 

    # matching_url = {}

    # if params[:random_string]
    #   matching_url = Url.find_url(params[:random_string])
    #   Url.redirect_counter(random_string)
    #   redirect_to matching_url.link 
    # elsif
    #   matching_url = Url.find_url(params[:my_string])
    #   Url.redirect_counter(random_string)
    #   redirect_to matching_url.link 
    # else 
    #   render file: "/Users/carinaho/Development/ritly/public/404.html"
    # end 
    random_string = params[:random_string] 
    matching_url = Url.find_url(random_string)

    if matching_url 
      # matching_url.build_visit ?? Returns undefined method 
      matching_url.visits.create(ip_address: request.remote_ip )
        
        Url.redirect_counter(random_string)
       redirect_to matching_url.link 
     else 
      
     end

  end 
    
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Ritly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/_find.html.erb
<form action="/urls/<%= @url.id %>" method="post"> 
	<input name="_method" type="hidden" value="put"> 
	<input type="text" name="url[link]" value="<%= @url.link %>"> 
	<input type="text" name="url[random_string]" value="<%= @url.random_string %>">
	<input type="text" name="url[my_string]" value="<%= @url.my_string %>">

	<%= token_tag form_authenticity_token %>

	<button type="button" class="btn btn-default">Default</button>
	

</form> 

app/views/urls/edit.html.erb
<%= render "find" %> 

app/views/urls/index.html.erb
<h1>All urls</h1>

<% @urls.each do |url| %>
    <li>
      Link: <%= url.link %></br>
      Shortened url: <%= url.random_string %></br>
      Link nickname: <%= url.my_string %> </br>
    </li>

    
<% end %>

app/views/urls/new.html.erb
<h1>Enter a URL to shorten and give it a custom nickname:</h1> </br> 

<form action="/urls" method="post">
	<p>Enter the link:</p><input type="text" name="url[link]"></br>
	<p>Give it a nickname:</p><input type="text" name="url[my_string]"></br></br>

    <%= token_tag form_authenticity_token %>

    <button> Generate random code </button>
</form>

app/views/urls/preview.html.erb
<h1>Preview page</h1>

Link: <%= @url %> </br>

<iframe src="<%= @url %>" width="1200px" height="600px">
<p>No preview available</p> 
</iframe>

app/views/urls/show.html.erb
Link: <%= @new_url.link %></br> 

Your random code is: <%= @new_url.random_string %> </br> 

Redirect counter: <%= @count %> </br> 
<table style="width:300px" border="2px" border-space="3px">
Dates and IP Addresses of visits: 
  <tr>
    <th>Dates</th>
    <th>User IP address</th>
  </tr>

<% @visits.each do |visit| %>
<tr>
<td><%= visit.created_at %></td> 
<td>&nbsp;&nbsp;&nbsp;&nbsp;<%= visit.ip_address %></td>
</tr>
<% end %>
</table>

</br>



<%= link_to "Shorten another URL", url_new_path %> </br> 

<%= link_to "See all URLs", urls_path %> 